### ISSUE TITLE
Extension for time manipulation

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/Clock#1]
Roadmap
- [x] extension for registering datetime as a service
- [ ] extend and make datetime immutable
- [ ] create date object
- [ ] create time object
- [ ] wrap that fucking interval thing that makes no sense
- [ ] locale formaters (using intl maybe?)

**Comment by fprochazka** [comment]
Out of scope.
